//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeValues
    {
        public int ID { get; set; }
        public string AttrValue { get; set; }
        public int AttrId { get; set; }
    
        public virtual Attributes Attributes { get; set; }
    }
}
