//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Books
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }
       
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Price is required")]      
        [RegularExpression(@"^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$", ErrorMessage = "enter decimal value of format $9.99")]

        public decimal Price { get; set; }
        public Nullable<int> PageCount { get; set; }
        public string BookDescription { get; set; }
        public string Picture { get; set; }
        public int CountryId { get; set; }
        public int AuthorId { get; set; }
        public int GenerId { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Geners Geners { get; set; }
    }
}
